name: CMake

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/cmake.yml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout current repo  
      uses: actions/checkout@v3

    - name: install dependencies
      run: sudo apt update && \
           sudo apt upgrade && \
           sudo apt install make zlib1g-dev libssl-dev gperf cmake g++

    - name: Build
      # Build your program with the given configuration
      run: mkdir build && \
           cd build && \
           cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=.. .. && \
           cmake --build . -j "$(nproc)"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')